package org.guide.gameboy.video.queue;

/**
 * Represents the possible sources for a pixel.
 *
 * @author Brendan Jones
 */
public enum PixelSource {

    /**
     * The pixel was generated by a background tile.
     */
    BACKGROUND,

    /**
     * The pixel was generated by a window tile.
     */
    WINDOW,

    /**
     * The pixel was generated by a sprite.
     */
    SPRITE

}
